### ISSUE TITLE
Is there a Julia version under development?

### ISSUE THREAD

**Issue by sambitdash** [norvig/paip-lisp#1]
Hi @norvig, 

Just saw the Python version is available for sometime now. Is there a Julia version under development under your guidance?

regards,

Sambit

**Comment by norvig** [comment]
No. It would be nice to have an efficient yet expressive language, like `Julia` or `Go`.

**Comment by sambitdash** [comment]
I may need a few of the text algorithms as part of my current assignments. If I get to implement some of them will share those.

**Comment by norvig** [comment]
Thanks!
