### ISSUE TITLE
Errata in chapter 4

### ISSUE THREAD

**Issue by marcellowoods** [norvig/paip-lisp#108]
in the function

`(defun achieve (state goal goal-stack)
  "A goal is achieved if it already holds,
  or if there is an appropriate op for it that is applicable."
  (dbg-indent :gps (length goal-stack) "Goal: "a" goal)
  (cond ((member-equal goal state) state)
      ((member-equal goal goal-stack) nil)
      (t (some #'(lambda (op) (apply-op state goal op goal-stack))
          (find-all goal *ops* :test #'appropriate-p)))))`

 `(dbg-indent :gps (length goal-stack) "Goal: "a" goal)`
should be:
  `(dbg-indent :gps (length goal-stack) "Goal: ~a" goal)`

**Comment by namin** [comment]
:+1:

**Comment by arnfaldur** [comment]
@marcellowoods you can edit the file and create a pull request directly on the github website. It's much easier for the maintainers to simply merge the change instead of fixing it themselves.

**Comment by pronoiac** [comment]
This was resolved by #114.
