### ISSUE TITLE
suggestion: add an info page to ebook?

### ISSUE THREAD

**Issue by pronoiac** [norvig/paip-lisp#149]
Rough drafts of the ebooks are nearing; I've [saved drafts of releases](https://github.com/norvig/paip-lisp/releases). Those ebooks could spread outside GitHub. Adding an info page early in the book might be a good idea, which could include, as examples: 

* "There's a collaborative effort at our GitHub repo. We're working on this in public, together - see *https://github.com/norvig/paip-lisp .* Corrections are welcome as PRs or Issues. For updates / newer versions, check Releases." 
* Plz don't charge for this / if you paid for this ebook, [fill in blank - email? File an issue? Ask for a refund?]
* "This is a snapshot of the text in the repo as of, say, 2022-04-09"; the date's also in the book title and file names right now
* an email address, like, "plz email corrections to ___, attn: PAIP corrections", though a PR or Issue on the repo's probably preferable by far
* this book's open source, under the MIT license, not public domain
* a 2022 copyright 

(I haven't yet posted those ebook releases because I'm not sure if it would be overstepping or if the situation is more "I trust you, go nuts".) 

Thoughts?

**Comment by norvig** [comment]
"I trust you."

But you raise a lot of issues; maybe we could have a brief conversation?

**Comment by pronoiac** [comment]
Sure thing! I dropped you an email.
