### ISSUE TITLE
use Github releases for large file distribution.

### ISSUE THREAD

**Issue by snmsts** [norvig/paip-lisp#15]
https://help.github.com/articles/about-releases/

> We don't limit the total size of your binary release files, nor the bandwidth used to deliver them. However, each individual file must be under 2 GB in size.

It seems enough for current PDF.

**Comment by norvig** [comment]
When I try to upload with the "upload files" button on the project page, I get

`Yowza, that’s a big file. Try again with a file smaller than 25MB.`

Maybe I need to upload through GitHub desktop or some other way? Does anyone know?

**Comment by nticaric** [comment]
Large files can only packed as a release. So in order to do this, you could go to 

https://github.com/norvig/paip-lisp/releases/new

Create a new release and upload the pdf there. I guess this should work

**Comment by eshellman** [comment]
@nticaric is correct, uploads in the "release" are not subject to the git size limits; in general you do not want distributions to be in git - you want the source files for the distros in git. The other reason you don't want distribution files in git is that GitHub will throttle direct downloads from the source tree, but won't throttle release distributions

**Comment by snmsts** [comment]
I tried to register paip-lisp into Quicklisp (defact package manager for common lisp) but it is refused because of the file size. So removing pdf from this repository could have benefit aside from just lessen the clone time.

**Comment by tygruletz** [comment]
Hi. I try to upload an 3 kb file using https://github.com/account/project/upload and I get error:
`Yowza, that’s a big file. Try again with a file smaller than 25MB.`
My file is a `.xcdatamodeld` (CoreData Model) - 3 kb size
Do you know how can I avoid this bug ?

**Comment by ninjaneerX** [comment]
> Hi. I try to upload an 3 kb file using https://github.com/account/project/upload and I get error:
> `Yowza, that’s a big file. Try again with a file smaller than 25MB.`
> My file is a `.xcdatamodeld` (CoreData Model) - 3 kb size
> Do you know how can I avoid this bug ?

I just ran into the same issue. Try committing from the desktop application.

**Comment by YSRathor** [comment]
I too have the exact same "Yowza, that’s a big file. Try again with a file smaller than 25MB.", which is highly irritating, considering that the files I wish to upload are well under 25MB.

**Comment by dhruvsingh14** [comment]
lol same here, and i don't use the desktop application precisely because I can get away with uploading. plz help

**Comment by masagrator** [comment]
This is a github issue. It also shows for my files in my repos. Only is not showing when I upload only file or folder with files (without folders inside).
I've contacted github in this case.

**Comment by suziGeek** [comment]
Same issue here - my files are much smaller than 25MB. Is this a bug. I've uploaded this build before with out this issue but the past 3 days its been going on. I managed to upload via bash window but I'm too new to it and I cannot get another push to work from there.

**Comment by pronoiac** [comment]
Hi all, this issue is about a Lisp ebook, not supporting uploads to Github for every project in the world. 

We haven't posted releases yet - that's pending approval by @norvig - but people are coming here by google and keywords for the wrong reasons, so I'm going to close this issue for now.

**Comment by kingdavid24** [comment]
Hi, i got the same problem Yowza, that’s a big file. Try again with a file smaller than 25MB.

**Comment by pronoiac** [comment]
This issue is resolved. I'm locking the conversation.
