### ISSUE TITLE
CMU Python 

### ISSUE THREAD

**Issue by fayolle** [norvig/paip-lisp#190]
https://github.com/norvig/paip-lisp/blob/f589ad5b25854e8fc0ddb126617713669f9faaf8/docs/chapter9.md?plain=1#L97 
Shouldn't it be CMU Lisp instead of CMU's Python?

**Comment by Hexstream** [comment]
CMU Common Lisp's compiler is called Python.

**Comment by fayolle** [comment]
I didn't know. That's interesting. Thank you.
