### ISSUE TITLE
Markdown - target version? Hard line breaks?

### ISSUE THREAD

**Issue by pronoiac** [norvig/paip-lisp#29]
I thought we were targeting [GitHub Flavored Markdown,](https://github.github.com/gfm/) but [hard line breaks](https://github.github.com/gfm/#hard-line-breaks) aren't rendering well. Compare the quote at the start of chapter 2 over [on the repo](https://github.com/norvig/paip-lisp/blob/master/docs/chapter2.md) (good!) to [the online version of the book](https://norvig.github.io/paip-lisp/#/chapter2) (not good).

I think the online version uses [docsify,](https://docsify.js.org/) which uses [marked,](https://github.com/markedjs/marked) which seems to have an optional parameter to enable gfm. I set up a local server and experimented with the `$docsify` portion in [docs/index.html](https://github.com/norvig/paip-lisp/blob/master/docs/index.html), but I was unable to get it working. Help, or suggestions?

**Comment by pronoiac** [comment]
Got it! Double trailing spaces work in both.

**Comment by norvig** [comment]
Yeah, I got burned by the double trailing spaces before ...
