### ISSUE TITLE
Exercise character

### ISSUE THREAD

**Issue by nticaric** [norvig/paip-lisp#9]
In the print version each exercise starts with a monitor with a question mark. What would be the best replacement for this in the text file? 

<img width="629" alt="805b1" src="https://user-images.githubusercontent.com/824840/36799360-4dc25596-1cad-11e8-9124-ccff934cc949.png">
Here are some propositions:

1. &#9632;
2. &#9635;
3. &#9654;
4. &#9672;
5. &#9673;
6. &#8226;
7. anything else?

**Comment by norvig** [comment]
I like 2. And I would think that we want the answers to questions to be hidden by default, with a triangle to click on to reveal the answer.

I'm wondering how else an online version can be enhanced:
- Link to the Common Lisp Hyperspec for each builtin function.
- Link to my code for the functions I define (Link within the book, or to the Github files?)
- Ability to run code in the browser.

**Comment by nticaric** [comment]
@norvig Here's my vision of the online book. I played only with the first chapter and it's obviously not complete but just wanted your opinion if we should move in this direction.

https://nticaric.github.io/paip-lisp/#/chapter1

Each chapter would be broken down into its own file and would be markdown flavored. Code highlighting would also look nice as shown here

https://nticaric.github.io/paip-lisp/#/code

If you like it, I'll create a pull request

**Comment by norvig** [comment]
Great start! That looks very nice, both the overall layout and the code highlighting. I think we want a serif font for the body text, to make it stand out more from sans-serif code font. Somebody helpfully posted a comment on the fonts used in the original book; I'm not sure if they would be best for online viewing. For the "evaluates to" arrow, I think we want `&rArr;` &rArr;

**Comment by norvig** [comment]
On the code highlighting: the orange colored symbols are not quite right. It seems okay that `defun`, `if`, `lambda`, etc. are highlighted, but other special forms like `setf` are not; also some functions like  `append` and `cons` are highlighted, but most functions are not.

**Comment by nticaric** [comment]
Ok, I guess we have to play a little bit with the code highlighting plugin. It's from

https://github.com/akirak/prism-emacs-lisp

The project seems to be pretty young and in development. Maybe @akirak could address some of those issues

**Comment by norvig** [comment]
There are other highlighters, like `highlightjs.org` or [code-prettify](https://github.com/google/code-prettify).

**Comment by akirak** [comment]
@nticaric Thanks for mentioning the plugin, but it needs rework due to my lack of expertise in Lisp and regular expressions. There is another guy [rewriting it](https://github.com/PrismJS/prism/pull/1297) so that it can be merged into the code base of PrismJS.

**Comment by aarvid** [comment]
Re: highlighting

[https://github.com/orthecreedence/highlight-lisp](https://github.com/orthecreedence/highlight-lisp)

I have used this and is used by the [Common Lisp Cookbook](https://lispcookbook.github.io/cl-cookbook/)

It is specific to Common Lisp

**Comment by nticaric** [comment]
Thanks @aarvid. This one seems to be working pretty well. I'll created a [PR](https://github.com/norvig/paip-lisp/pull/18) for this
