### ISSUE TITLE
Hi. I try to upload an 3 kb file using https://github.com/account/project/upload and I get error:

### ISSUE THREAD

**Issue by advaymehta009** [norvig/paip-lisp#98]
Hi. I try to upload an 3 kb file using https://github.com/account/project/upload and I get error:
`Yowza, that’s a big file. Try again with a file smaller than 25MB.`
My file is a `.xcdatamodeld` (CoreData Model) - 3 kb size
Do you know how can I avoid this bug ?

_Originally posted by @tygruletz in https://github.com/norvig/paip-lisp/issues/15#issuecomment-523888426_

**Comment by pronoiac** [comment]
This is not Github support.
